# Generated by Django 2.1.7 on 2019-03-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazovTextu', models.CharField(max_length=100)),
                ('kapitola', models.CharField(max_length=100)),
                ('strana', models.PositiveIntegerField(default=1)),
                ('riadok', models.PositiveIntegerField(default=1)),
                ('origText', models.TextField(default='n/a')),
                ('otLanguage', models.CharField(default='n/a', max_length=4)),
                ('translatedText', models.TextField(default='n/a')),
                ('ttLanguage', models.CharField(default='n/a', max_length=4)),
            ],
        ),
    ]
